NATION_DROPDOWN = 'nation-dropdown'
SELECT_ALL_NATIONS_BUTTON = 'select-all-nations-button'

BAR_CHART = 'bar-chart'
F_PIE_CHART = 'f-pie-chart'
F_LINE_CHART = 'f-line-chart'
F_BAR_CHART = 'f-bar-chart'
G_PIE_CHART = 'g-pie-chart'
IR_LINE_CHART = 'ir-line-chart'
FE_LINE_CHART = 'fe-line-chart'